### ISSUE TITLE
Update letsencrypt dependency from danzilio/letsencrypt to voxpupuli/puppet-letsencrypt

### ISSUE THREAD

**Issue by guillett** [pgassmann/puppet-letsencrypt_nginx#12]
From https://forge.puppet.com/danzilio/letsencrypt to https://github.com/voxpupuli/puppet-letsencrypt

**Comment by pgassmann** [comment]
/close
This is already done in newest release.

Am 28.03.2017 10:22 nachm. schrieb "guillett" <notifications@github.com>:

**Comment by guillett** [comment]
Sorry, I `fetched` but didn't `checked out` the new master. Great job !
