### ISSUE TITLE
'letsencrypt_nginx_firstrun' exec should specify a path

### ISSUE THREAD

**Issue by JayH5** [pgassmann/puppet-letsencrypt_nginx#2]
With the default Puppet config, the exec will fail to run because `mkdir` and `echo` are not qualified:

`Failed to apply catalog: Validation of Exec[set letsencrypt_nginx_firstrun fact] failed: 'mkdir -p /etc/facter/facts.d/ && echo "letsencrypt_nginx_firstrun=SUCCESS" > /etc/facter/facts.d/letsencrypt_nginx.txt' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppetlabs/code/environments/production/modules/letsencrypt_nginx/manifests/init.pp:62`

Adding a `path => ['/bin']` to the exec I think should fix things on most systems.

**Comment by JayH5** [comment]
Oops sorry.. I see #1 now...

**Comment by pgassmann** [comment]
Thanks anyways.

I could change this if it's not common practice to have a global Exec path default. In the environments I worked till now, this was always the case and it keeps the manifests simpler.

http://www.puppetcookbook.com/posts/set-global-exec-path.html

cc @cburn
