### ISSUE TITLE
migrate jfryman-nginx to puppet-nginx

### ISSUE THREAD

**Issue by danielburrell** [pgassmann/puppet-letsencrypt_nginx#7]
puppet-nginx has taken over maintenance of jfryman-nginx going forward.

Currently installing your module results in this error:

Error: Could not install module 'pgassmann-letsencrypt_nginx' (v1.1.3)
  Dependency 'jfryman-nginx' (v999.999.999) would overwrite /etc/puppet/modules/nginx
    Currently, 'puppet-nginx' (v0.5.0) is installed to that directory
    Use `puppet module install --ignore-dependencies` to install only this module

**Comment by pgassmann** [comment]
Thanks for bringing this to my attention. Will look into that
https://github.com/voxpupuli/puppet-nginx/

Did it work with the new module when you ignored the dependencies?

**Comment by danielburrell** [comment]
No worries

Haven't got there yet, encountered something else unrelated :( will get round to it in a week or so. Thanks for the module.

**Comment by pgassmann** [comment]
Fixed. Is now dependent on puppet-nginx v0.6.0 or later. Be aware of the breaking changes in puppet-nginx and so also in letsencrpyt_nginx. Especially the rename of vhost to server
