### ISSUE TITLE
SSL only vhost places acme-challenge inside non-existing HTTP server block

### ISSUE THREAD

**Issue by qte** [pgassmann/puppet-letsencrypt_nginx#8]
Not sure if this is an issue with puppet-letsencrypt_nginx or the nginx module.

Trying to setup a SSL only vhost by setting `ssl = true` and `listen_port = 443` generates an invalid vhost configuration file.

Sample puppet snippet:

	class { 'nginx':
	}
	
	# Catch all vhost
	nginx::resource::vhost { '_':
		www_root => '/usr/share/nginx/html'
	}

	nginx::resource::vhost { 'test.example.org':
		proxy => 'http://localhost:8081',
		ssl => true,
		#listen_port => 443,
		ssl_key => '/etc/letsencrypt/live/test.example.org/privkey.pem',
		ssl_cert => '/etc/letsencrypt/live/test.example.org/fullchain.pem'
	}

	class { ::letsencrypt:
		email => 'email@example.org',
    }

	class { 'letsencrypt_nginx':
		firstrun_webroot => '/var/lib/letsencrypt/webroot',
		vhosts => {
			'test.example.org' => {}
		}
	}

Adding listen_port => 443 and running puppet apply, results in the following change. Which nginx can't use.

	--- /etc/nginx/sites-available/test.example.org.conf	2017-01-08 17:48:31.578264617 +0100
	+++ /tmp/puppet-file20170108-9702-dvle14	2017-01-08 17:58:08.858259344 +0100
	@@ -1,23 +1,3 @@
	-# MANAGED BY PUPPET
	-server {
	-  listen *:80;
	-  server_name           test.example.org;
	-
	-  index  index.html index.htm index.php;
	-
	-  access_log            /var/log/nginx/test.example.org.access.log combined;
	-  error_log             /var/log/nginx/test.example.org.error.log;
	-
	-  location / {
	-
	-    proxy_pass            http://localhost:8081/;
	-    proxy_read_timeout    90;
	-    proxy_connect_timeout 90;
	-    proxy_redirect        off;
	-    proxy_set_header      Host $host;
	-    proxy_set_header      X-Real-IP $remote_addr;
	-    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
	-  }
	
	   location /.well-known/acme-challenge {
	     auth_basic           "off";
	@@ -25,7 +5,6 @@
	     root      /var/lib/letsencrypt/webroot;
	     index     index.html index.htm index.php;
	   }
	-}
	 # MANAGED BY PUPPET
	 server {
	   listen       *:443 ssl;

**Comment by qte** [comment]
Switched to puppet-nginx and error persists.

    $ puppet module install pgassmann-letsencrypt_nginx
    /etc/puppet/modules
    └─┬ pgassmann-letsencrypt_nginx (v1.2.1)
      ├── danzilio-letsencrypt (v1.0.0)
      ├─┬ puppet-nginx (v0.5.0)
      │ ├── puppetlabs-apt (v2.2.2)
      │ └── puppetlabs-concat (v2.2.0)
      └── puppetlabs-stdlib (v4.12.0)

**Comment by pgassmann** [comment]
what is the error of nginx? what is the complete vhost config file? is the acme-challenge location left over without the server with listen *:80

That probably cannot work, because for the challenge it needs a server on port 80

I suggest you leave the non-ssl on and enable rewrite to https:

```
nginx::resource::vhost { 'test.example.org':
	proxy => 'http://localhost:8081',
	ssl => true,
        rewrite_to_https =>  true,
	ssl_key => '/etc/letsencrypt/live/test.example.org/privkey.pem',
	ssl_cert => '/etc/letsencrypt/live/test.example.org/fullchain.pem'
}
```

**Comment by pgassmann** [comment]
With puppet-nginx v0.6.0 it is `server` instead of `vhost` and `ssl_redirect` instead of `rewrite_to_https`
```
nginx::resource::server { 'test.example.org':
	proxy => 'http://localhost:8081',
	ssl => true,
        ssl_redirect =>  true,
	ssl_key => '/etc/letsencrypt/live/test.example.org/privkey.pem',
	ssl_cert => '/etc/letsencrypt/live/test.example.org/fullchain.pem'
}
```
