### ISSUE TITLE
incompatible with puppet/nginx v0.6.0

### ISSUE THREAD

**Issue by axolander** [pgassmann/puppet-letsencrypt_nginx#9]
Unfortunately, the guys at puppet-nginx simply renamed nginx::resource::vhost to nginx::resource::server without taking care of backwards compatibility
https://github.com/voxpupuli/puppet-nginx/issues/348

this should be fixed here :)

regards
@axolander

**Comment by pgassmann** [comment]
This is fixed with the new version 2.0.1
